BEGIN TRANSACTION;
DROP TABLE IF EXISTS "Orders";
CREATE TABLE IF NOT EXISTS "Orders" (
	"ID"	INTEGER NOT NULL,
	"Name"	TEXT NOT NULL,
	"Phone"	INTEGER NOT NULL,
	"Comment"	TEXT NOT NULL,
	PRIMARY KEY("ID" AUTOINCREMENT)
);
COMMIT;
